// <auto-generated />
using System;
using L.GastosProdutos.Core.Infra.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L.GastosProdutos.Core.Infra.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103201139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("L.GastosProdutos.Core.Domain.Entities.Packing.PackingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packings");
                });

            modelBuilder.Entity("L.GastosProdutos.Core.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("L.GastosProdutos.Core.Domain.Entities.Recipe.RecipeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SellingValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("L.GastosProdutos.Core.Domain.Entities.Recipe.RecipeEntity", b =>
                {
                    b.OwnsMany("L.GastosProdutos.Core.Domain.Entities.Packing.PackingValueObject", "Packings", b1 =>
                        {
                            b1.Property<string>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PackingId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PackingName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("TEXT");

                            b1.HasKey("RecipeId", "PackingId");

                            b1.ToTable("RecipePackings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("L.GastosProdutos.Core.Domain.Entities.Recipe.IngredientsValueObject", "Ingredients", b1 =>
                        {
                            b1.Property<string>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("IngredientPrice")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("TEXT");

                            b1.HasKey("RecipeId", "ProductId");

                            b1.ToTable("RecipeIngredients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Packings");
                });
#pragma warning restore 612, 618
        }
    }
}
